[package]
name = "directed-scm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
rand = "*"
rand_xoshiro = { version = "*", features = ['serde1'] }
clap = { version = "3.0.8", features = ["derive"] }
rayon = "*"
hdf5 = "*"
ndarray = "*"
serde = { version = "1.0", features = ["derive"] }
bincode = "*"
indexmap = {version = "*", features = ["serde"] }

[build-dependencies]
#bindgen = "*"
cc = "*"

[profile.release]
debug = true
